# Generated by Django 3.2.9 on 2022-02-04 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='datosPaciente',
            fields=[
                ('hayVacios', models.BooleanField(default=False)),
                ('cod_pac', models.CharField(help_text='Primera letra del nombre + primera letra del apellido + últimos 3 dígitos del dni.', max_length=64, primary_key=True, serialize=False)),
                ('cod_doc', models.CharField(max_length=64)),
                ('apellidoYNombre', models.CharField(blank=True, help_text='Apellido y nombre del paciente. No es obligatorio', max_length=64)),
                ('fechaDeRegistro', models.CharField(max_length=64)),
                ('dni', models.CharField(blank=True, max_length=9)),
                ('nacionalidad', models.CharField(max_length=64)),
                ('fechaDeNacimiento', models.CharField(max_length=64)),
                ('sexo', models.IntegerField(choices=[(1, 'Femenino'), (2, 'Masculino')])),
                ('estadoCivil', models.IntegerField(choices=[(1, 'Soltero'), (2, 'Casado/concubino'), (3, 'Separado/divorciado'), (4, 'Viudo')])),
                ('escolaridad', models.IntegerField()),
                ('idProvincia', models.IntegerField(choices=[(1, 'Buenos Aires'), (2, 'Córdoba'), (3, 'Santa Fe'), (4, 'Tucumán'), (5, 'Misiones'), (6, 'Corrientes'), (7, 'Entre Ríos'), (8, 'Formosa'), (9, 'Chaco'), (10, 'San Luís'), (11, 'San Juan'), (12, 'Mendoza'), (13, 'Salta'), (14, 'Jujuy'), (15, 'Catamarca'), (16, 'La Rioja'), (17, 'La Pampa'), (18, 'Tierra Del Fuego'), (19, 'Rio Negro'), (20, 'Chubut'), (21, 'Neuquén'), (22, 'Santa Cruz'), (23, 'Santiago Del Estero'), (24, 'CABA')])),
                ('idArea', models.IntegerField(choices=[(1, 'Urbana'), (2, 'Rural')])),
                ('etnia', models.IntegerField(choices=[(1, 'Caucásico'), (2, 'Mestizo'), (3, 'Asiático'), (4, 'Afroamericano'), (5, 'Desconocido')])),
            ],
        ),
        migrations.CreateModel(
            name='datosHistorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artitrisPeriferica', models.IntegerField(blank=True, choices=[(1, 'Sí'), (0, 'No')])),
                ('entesitis', models.IntegerField(blank=True, choices=[(1, 'Sí'), (0, 'No')])),
                ('dactilitis', models.IntegerField(blank=True, choices=[(1, 'Sí'), (0, 'No')])),
                ('Psoriasis', models.IntegerField(blank=True, choices=[(1, 'Sí'), (0, 'No')])),
                ('eii', models.IntegerField(blank=True, choices=[(1, 'Sí'), (0, 'No')])),
                ('uveitis', models.IntegerField(blank=True, choices=[(1, 'Sí'), (0, 'No')])),
                ('buenaRespAINE', models.IntegerField(blank=True, choices=[(1, 'Sí'), (0, 'No')])),
                ('hisFamConEsP', models.IntegerField(blank=True, choices=[(1, 'Sí'), (0, 'No')])),
                ('portCReactiva', models.IntegerField(blank=True, choices=[(1, 'Sí'), (0, 'No')])),
                ('dolorLumbInflam', models.IntegerField(blank=True, choices=[(1, 'Sí'), (0, 'No')])),
                ('cod_pac', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tablasPacientes.datospaciente')),
            ],
        ),
        migrations.CreateModel(
            name='datosEstudios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HLAB27', models.IntegerField(blank=True, choices=[(1, 'Sí y fue positivo'), (2, 'Sí y fue negativo'), (3, 'No se hizo')])),
                ('resultHLAB27', models.IntegerField(blank=True, choices=[(2, 'No aplica'), (1, 'Positivo'), (0, 'Negativo')])),
                ('radioArtSacroiliacas', models.IntegerField(blank=True, choices=[(1, 'Grado 0 uni/bilateral'), (2, 'Grado 1 uni/bilateral'), (3, 'Grado 2 unilateral'), (4, 'Grado 2 bilateral'), (5, 'Grado 3 unilateral'), (6, 'Grado 3 bilateral'), (7, 'Grado 4 unilateral'), (8, 'Grado 4 bilateral'), (9, 'No se hizo')])),
                ('resultRadioArtSacroiliacas', models.IntegerField(blank=True, choices=[(1, 'Grado 0 uni/bilateral'), (2, 'Grado 1 uni/bilateral'), (3, 'Grado 2 unilateral'), (4, 'Grado 2 bilateral'), (5, 'Grado 3 unilateral'), (6, 'Grado 3 bilateral'), (7, 'Grado 4 unilateral'), (8, 'Grado 4 bilateral'), (9, 'No se hizo')])),
                ('RMSI', models.IntegerField(blank=True, choices=[(1, 'Sí y fue positivo'), (2, 'Sí y fue negativo'), (3, 'No se hizo')])),
                ('cumpleSIporRMsegunASAS', models.IntegerField(blank=True, choices=[(2, 'No aplica'), (1, 'Positivo'), (0, 'Negativo')])),
                ('cod_pac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablasPacientes.datospaciente')),
            ],
        ),
        migrations.CreateModel(
            name='datosEsPax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anioInicioEsPax', models.IntegerField()),
                ('anioDiagnostico', models.IntegerField()),
                ('cumpleCriterioASAS', models.IntegerField(choices=[(1, 'Sí'), (0, 'No')], default=0)),
                ('cumpleCriterioEANY', models.IntegerField(choices=[(1, 'Sí'), (0, 'No')], default=0)),
                ('subTipo', models.IntegerField(choices=[(1, 'Pura'), (2, 'Juvenil'), (3, 'Asociada a Artritis Psoriásica'), (4, 'Asociada a enfermedad Inflamatoria Intestinal (EII)'), (5, 'Artritis Reactiva')])),
                ('tipo', models.IntegerField(choices=[(1, 'No radiográfica'), (2, 'Radiográfica')], default=0)),
                ('cod_pac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablasPacientes.datospaciente')),
            ],
        ),
    ]
