# Generated by Django 3.2.9 on 2021-12-02 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='datosEsPax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anioInicioEsPax', models.IntegerField()),
                ('anioDiagnostico', models.IntegerField()),
                ('cumpleCriterioASAS', models.IntegerField()),
                ('cumpleCriterioEANY', models.IntegerField()),
                ('subTipo', models.IntegerField()),
                ('tipo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='datosEstudios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HLAB27', models.IntegerField()),
                ('resultHLAB27', models.IntegerField()),
                ('radioArtSacroiliacas', models.IntegerField()),
                ('resultRadioArtSacroiliacas', models.IntegerField()),
                ('RMSI', models.IntegerField()),
                ('cumpleSIporRMsegunASAS', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='datosHistorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artitrisPeriferica', models.IntegerField()),
                ('entesitis', models.IntegerField()),
                ('dactilitis', models.IntegerField()),
                ('Psoriasis', models.IntegerField()),
                ('eii', models.IntegerField()),
                ('uveitis', models.IntegerField()),
                ('buenaRespAINE', models.IntegerField()),
                ('hisFamConEsP', models.IntegerField()),
                ('portCReactiva', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='datosPaciente',
            fields=[
                ('doctor', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=64)),
                ('nombre', models.CharField(blank=True, max_length=64)),
                ('apellido', models.CharField(blank=True, max_length=64)),
                ('fechaDeRegistro', models.CharField(max_length=64)),
                ('dni', models.IntegerField()),
                ('nacionalidad', models.CharField(max_length=64)),
                ('fechaDeNacimiento', models.CharField(max_length=64)),
                ('sexo', models.IntegerField()),
                ('estadoCivil', models.IntegerField()),
                ('escolaridad', models.IntegerField()),
                ('idProvincia', models.IntegerField()),
                ('idArea', models.IntegerField()),
                ('etnia', models.IntegerField()),
            ],
        ),
    ]
