# Generated by Django 3.2.9 on 2021-12-02 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablasPacientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosestudios',
            name='cumpleSIporRMsegunASAS',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='datosestudios',
            name='resultHLAB27',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='datosestudios',
            name='resultRadioArtSacroiliacas',
            field=models.IntegerField(blank=True),
        ),
    ]
