# Generated by Django 3.2.9 on 2021-12-02 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tablasPacientes', '0002_auto_20211202_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosespax',
            name='doctor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='tablasPacientes.datospaciente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datosestudios',
            name='doctor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='tablasPacientes.datospaciente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datoshistorial',
            name='doctor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='tablasPacientes.datospaciente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datosestudios',
            name='cumpleSIporRMsegunASAS',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datosestudios',
            name='resultHLAB27',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datosestudios',
            name='resultRadioArtSacroiliacas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datospaciente',
            name='apellido',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='datospaciente',
            name='nombre',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
