# Generated by Django 3.2.9 on 2021-12-07 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablasPacientes', '0003_auto_20211202_0039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datosespax',
            old_name='doctor',
            new_name='cod_pac',
        ),
        migrations.RenameField(
            model_name='datosestudios',
            old_name='doctor',
            new_name='cod_pac',
        ),
        migrations.RenameField(
            model_name='datoshistorial',
            old_name='doctor',
            new_name='cod_pac',
        ),
        migrations.RenameField(
            model_name='datospaciente',
            old_name='codigo',
            new_name='cod_doc',
        ),
        migrations.RenameField(
            model_name='datospaciente',
            old_name='doctor',
            new_name='cod_pac',
        ),
        migrations.AlterField(
            model_name='datosespax',
            name='cumpleCriterioASAS',
            field=models.CharField(choices=[('1', 'Sí'), ('0', 'No')], max_length=64),
        ),
        migrations.AlterField(
            model_name='datosespax',
            name='cumpleCriterioEANY',
            field=models.CharField(choices=[('1', 'Sí'), ('0', 'No')], max_length=64),
        ),
        migrations.AlterField(
            model_name='datosespax',
            name='subTipo',
            field=models.CharField(choices=[('1', 'Pura'), ('2', 'Juvenil'), ('3', 'Asociada a Artritis Psoriásica'), ('4', 'Asociada a enfermedad Inflamatoria Intestinal (EII)'), ('5', 'Artritis Reactiva')], max_length=64),
        ),
        migrations.AlterField(
            model_name='datosespax',
            name='tipo',
            field=models.CharField(choices=[('1', 'No radiográfica'), ('2', 'Radiográfica')], max_length=64),
        ),
        migrations.AlterField(
            model_name='datosestudios',
            name='HLAB27',
            field=models.CharField(choices=[('1', 'Sí'), ('0', 'No')], max_length=64),
        ),
        migrations.AlterField(
            model_name='datosestudios',
            name='RMSI',
            field=models.CharField(choices=[('1', 'Sí'), ('0', 'No')], max_length=64),
        ),
        migrations.AlterField(
            model_name='datosestudios',
            name='cumpleSIporRMsegunASAS',
            field=models.CharField(blank=True, choices=[('1', 'Sí'), ('0', 'No')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='datosestudios',
            name='radioArtSacroiliacas',
            field=models.CharField(choices=[('1', 'Sí'), ('0', 'No')], max_length=64),
        ),
        migrations.AlterField(
            model_name='datosestudios',
            name='resultHLAB27',
            field=models.CharField(blank=True, choices=[('1', 'Positivo'), ('0', 'Negativo')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='datosestudios',
            name='resultRadioArtSacroiliacas',
            field=models.CharField(blank=True, choices=[('1', 'Positivo'), ('0', 'Negativo')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='datoshistorial',
            name='Psoriasis',
            field=models.CharField(choices=[('1', 'Sí'), ('0', 'No')], max_length=64),
        ),
        migrations.AlterField(
            model_name='datoshistorial',
            name='artitrisPeriferica',
            field=models.CharField(choices=[('1', 'Sí'), ('0', 'No')], max_length=64),
        ),
        migrations.AlterField(
            model_name='datoshistorial',
            name='buenaRespAINE',
            field=models.CharField(choices=[('1', 'Sí'), ('0', 'No')], max_length=64),
        ),
        migrations.AlterField(
            model_name='datoshistorial',
            name='dactilitis',
            field=models.CharField(choices=[('1', 'Sí'), ('0', 'No')], max_length=64),
        ),
        migrations.AlterField(
            model_name='datoshistorial',
            name='eii',
            field=models.CharField(choices=[('1', 'Sí'), ('0', 'No')], max_length=64),
        ),
        migrations.AlterField(
            model_name='datoshistorial',
            name='entesitis',
            field=models.CharField(choices=[('1', 'Sí'), ('0', 'No')], max_length=64),
        ),
        migrations.AlterField(
            model_name='datoshistorial',
            name='hisFamConEsP',
            field=models.CharField(choices=[('1', 'Sí'), ('0', 'No')], max_length=64),
        ),
        migrations.AlterField(
            model_name='datoshistorial',
            name='portCReactiva',
            field=models.CharField(choices=[('1', 'Sí'), ('0', 'No')], max_length=64),
        ),
        migrations.AlterField(
            model_name='datoshistorial',
            name='uveitis',
            field=models.CharField(choices=[('1', 'Sí'), ('0', 'No')], max_length=64),
        ),
        migrations.AlterField(
            model_name='datospaciente',
            name='estadoCivil',
            field=models.CharField(choices=[('1', 'Soltero'), ('2', 'Casado/concubino'), ('3', 'Separado/divorciado'), ('4', 'Viudo')], max_length=64),
        ),
        migrations.AlterField(
            model_name='datospaciente',
            name='etnia',
            field=models.CharField(choices=[('1', 'Caucásico'), ('2', 'Mestizo'), ('3', 'Asiático'), ('4', 'Afroamericano'), ('5', 'Desconocido')], max_length=64),
        ),
        migrations.AlterField(
            model_name='datospaciente',
            name='idArea',
            field=models.CharField(choices=[('1', 'Urbana'), ('2', 'Rural')], max_length=64),
        ),
        migrations.AlterField(
            model_name='datospaciente',
            name='idProvincia',
            field=models.CharField(choices=[('1', 'Buenos Aires'), ('2', 'Córdoba'), ('3', 'Santa Fe'), ('4', 'Tucumán'), ('5', 'Misiones'), ('6', 'Corrientes'), ('7', 'Entre Ríos'), ('8', 'Formosa'), ('9', 'Chaco'), ('10', 'San Luís'), ('11', 'San Juan'), ('12', 'Mendoza'), ('13', 'Salta'), ('14', 'Jujuy'), ('15', 'Catamarca'), ('16', 'La Rioja'), ('17', 'La Pampa'), ('18', 'Tierra Del Fuego'), ('19', 'Rio Negro'), ('20', 'Chubut'), ('21', 'Neuquén'), ('22', 'Santa Cruz'), ('23', 'Santiago Del Estero'), ('24', 'CABA')], max_length=64),
        ),
        migrations.AlterField(
            model_name='datospaciente',
            name='sexo',
            field=models.CharField(choices=[('1', 'Femenino'), ('2', 'Masculino')], max_length=64),
        ),
    ]
