# Generated by Django 3.2.9 on 2022-02-04 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablasPacientes', '0003_auto_20211202_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosestudios',
            name='cumpleSIporRMsegunASAS',
            field=models.CharField(choices=[(' ', 'No aplica'), ('1', 'Positivo'), ('0', 'Negativo')], max_length=64),
        ),
        migrations.AlterField(
            model_name='datosestudios',
            name='resultHLAB27',
            field=models.CharField(choices=[(' ', 'No aplica'), ('1', 'Positivo'), ('0', 'Negativo')], max_length=64),
        ),
        migrations.AlterField(
            model_name='datosestudios',
            name='resultRadioArtSacroiliacas',
            field=models.CharField(choices=[(' ', 'No aplica'), ('1', 'Positivo'), ('0', 'Negativo')], max_length=64),
        ),
        migrations.AlterField(
            model_name='datospaciente',
            name='apellido',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='datospaciente',
            name='nombre',
            field=models.CharField(max_length=64),
        ),
    ]
