# Generated by Django 3.2.9 on 2022-02-04 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tablasPacientes', '0005_auto_20220204_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datospaciente',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='datospaciente',
            name='nombre',
        ),
        migrations.AddField(
            model_name='datoshistorial',
            name='dolorLumbInflam',
            field=models.IntegerField(blank=True, choices=[(1, 'Sí'), (0, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='datospaciente',
            name='apellidoYNombre',
            field=models.CharField(blank=True, help_text='Apellido y nombre del paciente. No es obligatorio', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='datospaciente',
            name='hayVacios',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='datosespax',
            name='cumpleCriterioASAS',
            field=models.IntegerField(choices=[(1, 'Sí'), (0, 'No')], default=0),
        ),
        migrations.AlterField(
            model_name='datosespax',
            name='cumpleCriterioEANY',
            field=models.IntegerField(choices=[(1, 'Sí'), (0, 'No')], default=0),
        ),
        migrations.AlterField(
            model_name='datosespax',
            name='subTipo',
            field=models.IntegerField(choices=[(1, 'Pura'), (2, 'Juvenil'), (3, 'Asociada a Artritis Psoriásica'), (4, 'Asociada a enfermedad Inflamatoria Intestinal (EII)'), (5, 'Artritis Reactiva')]),
        ),
        migrations.AlterField(
            model_name='datosespax',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'No radiográfica'), (2, 'Radiográfica')], default=0),
        ),
        migrations.AlterField(
            model_name='datosestudios',
            name='HLAB27',
            field=models.IntegerField(blank=True, choices=[(1, 'Sí y fue positivo'), (2, 'Sí y fue negativo'), (3, 'No se hizo')], null=True),
        ),
        migrations.AlterField(
            model_name='datosestudios',
            name='RMSI',
            field=models.IntegerField(blank=True, choices=[(1, 'Sí y fue positivo'), (2, 'Sí y fue negativo'), (3, 'No se hizo')], null=True),
        ),
        migrations.AlterField(
            model_name='datosestudios',
            name='cumpleSIporRMsegunASAS',
            field=models.IntegerField(blank=True, choices=[(2, 'No aplica'), (1, 'Positivo'), (0, 'Negativo')], null=True),
        ),
        migrations.AlterField(
            model_name='datosestudios',
            name='radioArtSacroiliacas',
            field=models.IntegerField(blank=True, choices=[(1, 'Grado 0 uni/bilateral'), (2, 'Grado 1 uni/bilateral'), (3, 'Grado 2 unilateral'), (4, 'Grado 2 bilateral'), (5, 'Grado 3 unilateral'), (6, 'Grado 3 bilateral'), (7, 'Grado 4 unilateral'), (8, 'Grado 4 bilateral'), (9, 'No se hizo')], null=True),
        ),
        migrations.AlterField(
            model_name='datosestudios',
            name='resultHLAB27',
            field=models.IntegerField(blank=True, choices=[(2, 'No aplica'), (1, 'Positivo'), (0, 'Negativo')], null=True),
        ),
        migrations.AlterField(
            model_name='datosestudios',
            name='resultRadioArtSacroiliacas',
            field=models.IntegerField(blank=True, choices=[(1, 'Grado 0 uni/bilateral'), (2, 'Grado 1 uni/bilateral'), (3, 'Grado 2 unilateral'), (4, 'Grado 2 bilateral'), (5, 'Grado 3 unilateral'), (6, 'Grado 3 bilateral'), (7, 'Grado 4 unilateral'), (8, 'Grado 4 bilateral'), (9, 'No se hizo')], null=True),
        ),
        migrations.AlterField(
            model_name='datoshistorial',
            name='Psoriasis',
            field=models.IntegerField(blank=True, choices=[(1, 'Sí'), (0, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='datoshistorial',
            name='artitrisPeriferica',
            field=models.IntegerField(blank=True, choices=[(1, 'Sí'), (0, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='datoshistorial',
            name='buenaRespAINE',
            field=models.IntegerField(blank=True, choices=[(1, 'Sí'), (0, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='datoshistorial',
            name='cod_pac',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tablasPacientes.datospaciente'),
        ),
        migrations.AlterField(
            model_name='datoshistorial',
            name='dactilitis',
            field=models.IntegerField(blank=True, choices=[(1, 'Sí'), (0, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='datoshistorial',
            name='eii',
            field=models.IntegerField(blank=True, choices=[(1, 'Sí'), (0, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='datoshistorial',
            name='entesitis',
            field=models.IntegerField(blank=True, choices=[(1, 'Sí'), (0, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='datoshistorial',
            name='hisFamConEsP',
            field=models.IntegerField(blank=True, choices=[(1, 'Sí'), (0, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='datoshistorial',
            name='portCReactiva',
            field=models.IntegerField(blank=True, choices=[(1, 'Sí'), (0, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='datoshistorial',
            name='uveitis',
            field=models.IntegerField(blank=True, choices=[(1, 'Sí'), (0, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='datospaciente',
            name='cod_pac',
            field=models.CharField(help_text='Primera letra del nombre + primera letra del apellido + últimos 3 dígitos del dni.', max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='datospaciente',
            name='dni',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AlterField(
            model_name='datospaciente',
            name='estadoCivil',
            field=models.IntegerField(choices=[(1, 'Soltero'), (2, 'Casado/concubino'), (3, 'Separado/divorciado'), (4, 'Viudo')]),
        ),
        migrations.AlterField(
            model_name='datospaciente',
            name='etnia',
            field=models.IntegerField(choices=[(1, 'Caucásico'), (2, 'Mestizo'), (3, 'Asiático'), (4, 'Afroamericano'), (5, 'Desconocido')]),
        ),
        migrations.AlterField(
            model_name='datospaciente',
            name='idArea',
            field=models.IntegerField(choices=[(1, 'Urbana'), (2, 'Rural')]),
        ),
        migrations.AlterField(
            model_name='datospaciente',
            name='idProvincia',
            field=models.IntegerField(choices=[(1, 'Buenos Aires'), (2, 'Córdoba'), (3, 'Santa Fe'), (4, 'Tucumán'), (5, 'Misiones'), (6, 'Corrientes'), (7, 'Entre Ríos'), (8, 'Formosa'), (9, 'Chaco'), (10, 'San Luís'), (11, 'San Juan'), (12, 'Mendoza'), (13, 'Salta'), (14, 'Jujuy'), (15, 'Catamarca'), (16, 'La Rioja'), (17, 'La Pampa'), (18, 'Tierra Del Fuego'), (19, 'Rio Negro'), (20, 'Chubut'), (21, 'Neuquén'), (22, 'Santa Cruz'), (23, 'Santiago Del Estero'), (24, 'CABA')]),
        ),
        migrations.AlterField(
            model_name='datospaciente',
            name='sexo',
            field=models.IntegerField(choices=[(1, 'Femenino'), (2, 'Masculino')]),
        ),
    ]
