# Generated by Django 3.2.9 on 2022-02-04 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablasPacientes', '0006_auto_20220204_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datosespax',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='datosestudios',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='datoshistorial',
            name='doctor',
        ),
        migrations.AlterField(
            model_name='datosestudios',
            name='HLAB27',
            field=models.IntegerField(blank=True, choices=[(1, 'Sí y fue positivo'), (2, 'Sí y fue negativo'), (3, 'No se hizo')]),
        ),
        migrations.AlterField(
            model_name='datosestudios',
            name='RMSI',
            field=models.IntegerField(blank=True, choices=[(1, 'Sí y fue positivo'), (2, 'Sí y fue negativo'), (3, 'No se hizo')]),
        ),
        migrations.AlterField(
            model_name='datosestudios',
            name='cumpleSIporRMsegunASAS',
            field=models.IntegerField(blank=True, choices=[(2, 'No aplica'), (1, 'Positivo'), (0, 'Negativo')]),
        ),
        migrations.AlterField(
            model_name='datosestudios',
            name='radioArtSacroiliacas',
            field=models.IntegerField(blank=True, choices=[(1, 'Grado 0 uni/bilateral'), (2, 'Grado 1 uni/bilateral'), (3, 'Grado 2 unilateral'), (4, 'Grado 2 bilateral'), (5, 'Grado 3 unilateral'), (6, 'Grado 3 bilateral'), (7, 'Grado 4 unilateral'), (8, 'Grado 4 bilateral'), (9, 'No se hizo')]),
        ),
        migrations.AlterField(
            model_name='datosestudios',
            name='resultHLAB27',
            field=models.IntegerField(blank=True, choices=[(2, 'No aplica'), (1, 'Positivo'), (0, 'Negativo')]),
        ),
        migrations.AlterField(
            model_name='datosestudios',
            name='resultRadioArtSacroiliacas',
            field=models.IntegerField(blank=True, choices=[(1, 'Grado 0 uni/bilateral'), (2, 'Grado 1 uni/bilateral'), (3, 'Grado 2 unilateral'), (4, 'Grado 2 bilateral'), (5, 'Grado 3 unilateral'), (6, 'Grado 3 bilateral'), (7, 'Grado 4 unilateral'), (8, 'Grado 4 bilateral'), (9, 'No se hizo')]),
        ),
        migrations.AlterField(
            model_name='datoshistorial',
            name='Psoriasis',
            field=models.CharField(blank=True, choices=[(1, 'Sí'), (0, 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='datoshistorial',
            name='artitrisPeriferica',
            field=models.CharField(blank=True, choices=[(1, 'Sí'), (0, 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='datoshistorial',
            name='buenaRespAINE',
            field=models.CharField(blank=True, choices=[(1, 'Sí'), (0, 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='datoshistorial',
            name='dactilitis',
            field=models.CharField(blank=True, choices=[(1, 'Sí'), (0, 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='datoshistorial',
            name='dolorLumbInflam',
            field=models.CharField(blank=True, choices=[(1, 'Sí'), (0, 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='datoshistorial',
            name='eii',
            field=models.CharField(blank=True, choices=[(1, 'Sí'), (0, 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='datoshistorial',
            name='entesitis',
            field=models.CharField(blank=True, choices=[(1, 'Sí'), (0, 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='datoshistorial',
            name='hisFamConEsP',
            field=models.CharField(blank=True, choices=[(1, 'Sí'), (0, 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='datoshistorial',
            name='portCReactiva',
            field=models.CharField(blank=True, choices=[(1, 'Sí'), (0, 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='datoshistorial',
            name='uveitis',
            field=models.CharField(blank=True, choices=[(1, 'Sí'), (0, 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='datospaciente',
            name='apellidoYNombre',
            field=models.CharField(blank=True, help_text='Apellido y nombre del paciente. No es obligatorio', max_length=64),
        ),
    ]
