# Generated by Django 3.2.9 on 2022-02-04 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablasPacientes', '0008_alter_datosespax_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datoshistorial',
            name='Psoriasis',
            field=models.CharField(blank=True, choices=[(1, 'Sí'), (0, 'No')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='datoshistorial',
            name='artitrisPeriferica',
            field=models.CharField(blank=True, choices=[(1, 'Sí'), (0, 'No')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='datoshistorial',
            name='buenaRespAINE',
            field=models.CharField(blank=True, choices=[(1, 'Sí'), (0, 'No')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='datoshistorial',
            name='dactilitis',
            field=models.CharField(blank=True, choices=[(1, 'Sí'), (0, 'No')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='datoshistorial',
            name='dolorLumbInflam',
            field=models.CharField(blank=True, choices=[(1, 'Sí'), (0, 'No')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='datoshistorial',
            name='eii',
            field=models.CharField(blank=True, choices=[(1, 'Sí'), (0, 'No')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='datoshistorial',
            name='entesitis',
            field=models.CharField(blank=True, choices=[(1, 'Sí'), (0, 'No')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='datoshistorial',
            name='hisFamConEsP',
            field=models.CharField(blank=True, choices=[(1, 'Sí'), (0, 'No')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='datoshistorial',
            name='portCReactiva',
            field=models.CharField(blank=True, choices=[(1, 'Sí'), (0, 'No')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='datoshistorial',
            name='uveitis',
            field=models.CharField(blank=True, choices=[(1, 'Sí'), (0, 'No')], max_length=10, null=True),
        ),
    ]
