# Generated by Django 3.2.9 on 2022-02-04 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablasPacientes', '0009_auto_20220204_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosespax',
            name='cumpleCriterioASAS',
            field=models.IntegerField(choices=[('1', 'Sí'), ('0', 'No')], default=0),
        ),
        migrations.AlterField(
            model_name='datosespax',
            name='cumpleCriterioEANY',
            field=models.IntegerField(choices=[('1', 'Sí'), ('0', 'No')], default=0),
        ),
        migrations.AlterField(
            model_name='datosestudios',
            name='HLAB27',
            field=models.IntegerField(blank=True, choices=[(1, 'Sí y fue positivo'), (2, 'Sí y fue negativo'), (3, 'No se hizo')], null=True),
        ),
        migrations.AlterField(
            model_name='datosestudios',
            name='RMSI',
            field=models.IntegerField(blank=True, choices=[(1, 'Sí y fue positivo'), (2, 'Sí y fue negativo'), (3, 'No se hizo')], null=True),
        ),
        migrations.AlterField(
            model_name='datosestudios',
            name='cumpleSIporRMsegunASAS',
            field=models.IntegerField(blank=True, choices=[(2, 'No aplica'), (1, 'Positivo'), (0, 'Negativo')], null=True),
        ),
        migrations.AlterField(
            model_name='datosestudios',
            name='radioArtSacroiliacas',
            field=models.IntegerField(blank=True, choices=[(1, 'Grado 0 uni/bilateral'), (2, 'Grado 1 uni/bilateral'), (3, 'Grado 2 unilateral'), (4, 'Grado 2 bilateral'), (5, 'Grado 3 unilateral'), (6, 'Grado 3 bilateral'), (7, 'Grado 4 unilateral'), (8, 'Grado 4 bilateral'), (9, 'No se hizo')], null=True),
        ),
        migrations.AlterField(
            model_name='datosestudios',
            name='resultHLAB27',
            field=models.IntegerField(blank=True, choices=[(2, 'No aplica'), (1, 'Positivo'), (0, 'Negativo')], null=True),
        ),
        migrations.AlterField(
            model_name='datosestudios',
            name='resultRadioArtSacroiliacas',
            field=models.IntegerField(blank=True, choices=[(1, 'Grado 0 uni/bilateral'), (2, 'Grado 1 uni/bilateral'), (3, 'Grado 2 unilateral'), (4, 'Grado 2 bilateral'), (5, 'Grado 3 unilateral'), (6, 'Grado 3 bilateral'), (7, 'Grado 4 unilateral'), (8, 'Grado 4 bilateral'), (9, 'No se hizo')], null=True),
        ),
        migrations.AlterField(
            model_name='datoshistorial',
            name='Psoriasis',
            field=models.CharField(blank=True, choices=[('1', 'Sí'), ('0', 'No')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='datoshistorial',
            name='artitrisPeriferica',
            field=models.CharField(blank=True, choices=[('1', 'Sí'), ('0', 'No')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='datoshistorial',
            name='buenaRespAINE',
            field=models.CharField(blank=True, choices=[('1', 'Sí'), ('0', 'No')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='datoshistorial',
            name='dactilitis',
            field=models.CharField(blank=True, choices=[('1', 'Sí'), ('0', 'No')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='datoshistorial',
            name='dolorLumbInflam',
            field=models.CharField(blank=True, choices=[('1', 'Sí'), ('0', 'No')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='datoshistorial',
            name='eii',
            field=models.CharField(blank=True, choices=[('1', 'Sí'), ('0', 'No')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='datoshistorial',
            name='entesitis',
            field=models.CharField(blank=True, choices=[('1', 'Sí'), ('0', 'No')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='datoshistorial',
            name='hisFamConEsP',
            field=models.CharField(blank=True, choices=[('1', 'Sí'), ('0', 'No')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='datoshistorial',
            name='portCReactiva',
            field=models.CharField(blank=True, choices=[('1', 'Sí'), ('0', 'No')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='datoshistorial',
            name='uveitis',
            field=models.CharField(blank=True, choices=[('1', 'Sí'), ('0', 'No')], max_length=10, null=True),
        ),
    ]
