# Generated by Django 3.2.9 on 2022-02-04 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablasPacientes', '0010_auto_20220204_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datoshistorial',
            name='Psoriasis',
            field=models.CharField(blank=True, choices=[('1', 'Sí'), ('0', 'No')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='datoshistorial',
            name='artitrisPeriferica',
            field=models.CharField(blank=True, choices=[('1', 'Sí'), ('0', 'No')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='datoshistorial',
            name='buenaRespAINE',
            field=models.CharField(blank=True, choices=[('1', 'Sí'), ('0', 'No')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='datoshistorial',
            name='dactilitis',
            field=models.CharField(blank=True, choices=[('1', 'Sí'), ('0', 'No')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='datoshistorial',
            name='dolorLumbInflam',
            field=models.CharField(blank=True, choices=[('1', 'Sí'), ('0', 'No')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='datoshistorial',
            name='eii',
            field=models.CharField(blank=True, choices=[('1', 'Sí'), ('0', 'No')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='datoshistorial',
            name='entesitis',
            field=models.CharField(blank=True, choices=[('1', 'Sí'), ('0', 'No')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='datoshistorial',
            name='hisFamConEsP',
            field=models.CharField(blank=True, choices=[('1', 'Sí'), ('0', 'No')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='datoshistorial',
            name='portCReactiva',
            field=models.CharField(blank=True, choices=[('1', 'Sí'), ('0', 'No')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='datoshistorial',
            name='uveitis',
            field=models.CharField(blank=True, choices=[('1', 'Sí'), ('0', 'No')], default='', max_length=10),
        ),
    ]
