# Generated by Django 3.2.9 on 2022-02-04 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablasPacientes', '0011_auto_20220204_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosestudios',
            name='HLAB27',
            field=models.CharField(blank=True, choices=[('1', 'Sí y fue positivo'), ('2', 'Sí y fue negativo'), ('3', 'No se hizo')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='datosestudios',
            name='RMSI',
            field=models.CharField(blank=True, choices=[('1', 'Sí y fue positivo'), ('2', 'Sí y fue negativo'), ('3', 'No se hizo')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='datosestudios',
            name='cumpleSIporRMsegunASAS',
            field=models.CharField(blank=True, choices=[(2, 'No aplica'), (1, 'Positivo'), (0, 'Negativo')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='datosestudios',
            name='radioArtSacroiliacas',
            field=models.CharField(blank=True, choices=[('1', 'Grado 0 uni/bilateral'), ('2', 'Grado 1 uni/bilateral'), ('3', 'Grado 2 unilateral'), ('4', 'Grado 2 bilateral'), ('5', 'Grado 3 unilateral'), ('6', 'Grado 3 bilateral'), ('7', 'Grado 4 unilateral'), ('8', 'Grado 4 bilateral'), ('9', 'No se hizo')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='datosestudios',
            name='resultHLAB27',
            field=models.CharField(blank=True, choices=[(2, 'No aplica'), (1, 'Positivo'), (0, 'Negativo')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='datosestudios',
            name='resultRadioArtSacroiliacas',
            field=models.CharField(blank=True, choices=[('1', 'Grado 0 uni/bilateral'), ('2', 'Grado 1 uni/bilateral'), ('3', 'Grado 2 unilateral'), ('4', 'Grado 2 bilateral'), ('5', 'Grado 3 unilateral'), ('6', 'Grado 3 bilateral'), ('7', 'Grado 4 unilateral'), ('8', 'Grado 4 bilateral'), ('9', 'No se hizo')], default='', max_length=10),
        ),
    ]
