# Generated by Django 3.2.9 on 2022-02-04 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablasPacientes', '0013_alter_datosespax_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosespax',
            name='cumpleCriterioASAS',
            field=models.CharField(blank=True, choices=[('1', 'Sí'), ('0', 'No')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='datosespax',
            name='cumpleCriterioEANY',
            field=models.CharField(blank=True, choices=[('1', 'Sí'), ('0', 'No')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='datosespax',
            name='tipo',
            field=models.CharField(blank=True, choices=[('1', 'No radiográfica'), ('2', 'Radiográfica')], default='', max_length=10),
        ),
    ]
